#!/usr/bin/env bash
# Simple helper for running test scripts directly, since bats tends to be a
# little opaque.

set -euo pipefail

(( "$#" > 1 )) || echo "error: you must specify one or more test directories to execute" >&2

for testdir in "$@"; do
  for testfile in "$(dirname "$0")/$1/"*.sh; do
    echo ">>>> $testfile <<<<"
    bash "$testfile"
  done
done
